spring:
  application:
    name: Custom Queries
  datasource:
    url: jdbc:mysql://localhost:3306/devdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
